@startuml
box "app"
  participant ImportEndPoint
  participant BatchImporter
  participant JPA_PO_Repository
  participant JPA_POL_Repository
end box
box "core/UseCase"
  participant ImportPO
end box
box "core/Domain"
  participant PORepository
  participant POLRepository
  participant POFactory
end box

ImportEndPoint -\ BatchImporter: import
activate BatchImporter
  BatchImporter -> JPA_PO_Repository: insertOrUpdate
  BatchImporter -\ ImportPO: purchaseOrderImported
  activate ImportPO
    BatchImporter -> JPA_POL_Repository: insertOrUpdate
    BatchImporter -\ ImportPO: purchaseOrderLIneImported
    BatchImporter -\ ImportPO: purchaseOrderImportEnded
  deactivate ImportPO
return importEnqueued
@enduml
