@startuml
skinparam ParticipantPadding 10
skinparam BoxPadding 20
box "app"
  participant ImportEndPoint
  participant BatchImporter
  participant DocParser
  participant JDBCTemplate
end box
box "core/UseCase" #LightBlue
  participant ImportPO
end box
box "core/Domain" #Orange
  participant Validator
  participant PORepository
  participant PurchaseOrder
end box

ImportEndPoint -\ BatchImporter: import
BatchImporter --\ ImportEndPoint: importEnqueued
BatchImporter -> DocParser: parseHeader
BatchImporter -> JDBCTemplate: insertOrUpdate
BatchImporter -> DocParser: parseLine
BatchImporter -> JDBCTemplate: insertOrUpdate
BatchImporter -\ ImportPO: purchaseOrderImported
ImportPO -> PORepository: loadPOAggregate
PORepository -> PurchaseOrder ** : load
PurchaseOrder --> ImportPO
ImportPO -> Validator: validateAggregate
Validator -> PurchaseOrder
PurchaseOrder --> Validator
Validator --> ImportPO
ImportPO -> PurchaseOrder: markAsValid
ImportPO -> PORepository: storePurchaseOrder
@enduml
