@startuml
(Create New PurchaseOrder) as ImportPO
(Update Existing PurchaseOrder) as ImportExistingPO

(AllocatePurchaseOrderLineToBooking) as AllocatePOL

:Customer ERP System: as erp

:Action in another Service: as anotherService


erp --> ImportPO : import with PO data
erp --> ImportExistingPO : import with PO data

anotherService --> AllocatePOL : async. message with allocation information
@enduml
